server:
  port: 8300
spring:
  application:
    name: config-svc
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config
